# Default values for dash-front-back-end.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  enable4G: true
  enable5G: false

replicaCount: 1

version: "{{ .Chart.AppVersion }}"
#version: latest

image:
  repository: accelleran/dash-front-back-end
  pullPolicy: IfNotPresent

initImage:
  repository: accelleran/acc-generic-img
  pullPolicy: IfNotPresent
  tag: "0.7.1"

initConfig:
  kafkaUrl: "{{ .Release.Name }}-acc-kafka.{{ .Release.Namespace }}:9092"
  kafkaTopicsCheck: "accelleran.drax.4g.ric.raw.messages,accelleran.drax.4g.ric.raw.service_discovery,accelleran.drax.4g.ric.raw.ue_measurements,accelleran.drax.5g.ric.raw.cu_state,accelleran.drax.5g.ric.raw.ue_measurements,accelleran.drax.5g.ric.raw.pm_counters,accelleran.drax.5g.ric.raw.messages"
  
imagePullSecrets: 
  - name: accelleran-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0

service:
  enabled: true
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 31315
  portname: http
  protocol: TCP

websocketService:
  enabled: true
  type: NodePort
  port: 5001
  targetPort: 5001
  nodePort: 31316
  portname: "websocket"

config:
  config_id: "production"
  defaultServiceNamespace: "default"
  defaultOranNamespace: "default"
  grafanaURL: "10.20.20.20"
  grafanaPort: "30300"
  nodeApiURL: "10.20.20.20"
  nodePort: "30315"
  kafkaUrl: "10.20.20.20"
  kafkaPort: "31090"
  svcOrchestratorHost: "acc-service-orchestrator"
  svcOrchestratorPort: "80"
  svcMonitorHost: "acc-service-monitor"
  svcMonitorPort: "80"
  pcixAppPodName: "accelleran-drax-pci-010-pci-xapp-api"
  pcixAppPort: "80"
  ksqldbPodName: "10.20.20.20"
  ksqldbPort: "30533"
  LteRadioControllerLabel: "4G-Radio-Controller"
  apiUrl: "10.20.20.20"
  websocketPort: "31316"
  topologyExpired: 5000
  kafkaTopics:
    - "accelleran.drax.5g.ric.raw.cu_state"
    - "accelleran.drax.5g.ric.raw.ue_measurements"
    - "accelleran.drax.4g.ric.raw.network_state"
    - "accelleran.drax.all.ric.processed.anr"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

draxNodeSelectorEnabled: "false"

draxNodeSelector:
  draxName: "main"

tolerations: []

affinity: {}
